# Generated by Django 5.2.7 on 2025-11-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_name_en_us_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_type_ru',
        ),
    ]
