# Generated by Django 5.2.7 on 2025-11-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_post_post_type_en_us_remove_post_post_type_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creation_date_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='creation_date_ru',
        ),
    ]
